export const products = [
  {
    id: 1,
    name: "Men's Streetwear Fashion Style Big Pocket Cotton Long Sleeve Shirt Blue / XL",
    category: "Baju",
    price: 30,
    image: "/images/products/baju-1.png",
    isCart: false,
    description: "This shirt features a vibrant and eye-catching color and a solid pattern that will give you a happy feeling. Its long sleeve design makes it an ideal choice for men. The turn-down collar adds to comfort and stylish look. Its versatile design and great fit make it an ideal choice for casual occasions. Specifications Style: Casual Sleeve Style: Regular Sleeve Length(cm): Full Shirts Type: Casual Shirts Pattern Type: Solid Origin: CN(Origin) Model Number: C6112 Material: Cotton Item T",
  },
  {
    id: 2,
    name: "Casual Long Sleeve Plaid Shirt - jiu hong / XXL(65-70KG)",
    category: "Baju",
    price: 20,
    image: "/images/products/baju-2.png",
    isCart: false,
    description: "Regular fit Denim design Classic collar Long buttoned sleeve Patch pocket on the chest Button up The model is 187 cm tall and is wearing a size M",
  },
  {
    id: 3,
    name: "Men's Streetwear Fashion Style Big Pocket Cotton Long Sleeve Shirt Gray / XL",
    category: "Baju",
    price: 17,
    image: "/images/products/baju-3.png",
    isCart: false,
    description: "Navy Blue Preppy Long Sleeve Polyester Plaid Shirt Non-Stretch Spring/Fall Men Tops",
  },
  {
    id: 4,
    name: "Men's Streetwear Fashion Style Big Pocket Cotton Long Sleeve Shirt Gray / XL",
    category: "Baju",
    price: 17,
    image: "/images/products/baju-4.png",
    isCart: false,
    description: "Navy Blue Preppy Long Sleeve Polyester Plaid Shirt Non-Stretch Spring/Fall Men Tops",
  },
  {
    id: 5,
    name: "Men's Streetwear Fashion Style Big Pocket Cotton Long Sleeve Shirt Gray / XL",
    category: "Baju",
    price: 17,
    image: "/images/products/baju-5.png",
    isCart: false,
    description: "Navy Blue Preppy Long Sleeve Polyester Plaid Shirt Non-Stretch Spring/Fall Men Tops",
  },
  {
    id: 6,
    name: "Men's Streetwear Fashion Style Big Pocket Cotton Long Sleeve Shirt Gray / XL",
    category: "Baju",
    price: 17,
    image: "/images/products/baju-6.png",
    isCart: false,
    description: "Navy Blue Preppy Long Sleeve Polyester Plaid Shirt Non-Stretch Spring/Fall Men Tops",
  },
  {
    id: 7,
    name: "Ted Baker Mens SeyII Slim Fit Plain Trouser, Navy - Size 34W/32L",
    category: "Celana",
    price: 16,
    image: "/images/products/celana-1.png",
    isCart: false,
    description: "Rugged, functional, and to the point. The Operator Utility Shirt has a military look with a metropolitan fit and finish. The durable stone gray cotton shirt weight canvas is sure to be a favorite back to well-worn denim.",
  },
  {
    id: 8,
    name: "Ted Baker Mens SeyII Slim Fit Plain Trouser, Navy - Size 34W/32L",
    category: "Celana",
    price: 16,
    image: "/images/products/celana-2.png",
    isCart: false,
    description: "Rugged, functional, and to the point. The Operator Utility Shirt has a military look with a metropolitan fit and finish. The durable stone gray cotton shirt weight canvas is sure to be a favorite back to well-worn denim.",
  },
  {
    id: 9,
    name: "Ted Baker Mens SeyII Slim Fit Plain Trouser, Navy - Size 34W/32L",
    category: "Celana",
    price: 16,
    image: "/images/products/celana-3.png",
    isCart: false,
    description: "Rugged, functional, and to the point. The Operator Utility Shirt has a military look with a metropolitan fit and finish. The durable stone gray cotton shirt weight canvas is sure to be a favorite back to well-worn denim.",
  },
  {
    id: 10,
    name: "Ted Baker Mens SeyII Slim Fit Plain Trouser, Navy - Size 34W/32L",
    category: "Celana",
    price: 16,
    image: "/images/products/celana-4.png",
    isCart: false,
    description: "Rugged, functional, and to the point. The Operator Utility Shirt has a military look with a metropolitan fit and finish. The durable stone gray cotton shirt weight canvas is sure to be a favorite back to well-worn denim.",
  },
  {
    id: 11,
    name: "Batch Freelancer Men's Button Down Shirt in Aluminum Gray",
    category: "Jam",
    price: 10,
    image: "/images/products/jam-1.png",
    isCart: false,
    description: "White Casual Short Sleeve Cotton Plain Top Embellished Non-Stretch Summer Men Tops",
  },
  {
    id: 12,
    name: "RM 056-01 Tourbillon Sapphire",
    category: "Jam",
    price: 100,
    image: "/images/products/jam-2.png",
    isCart: false,
    description: "White Casual Short Sleeve Cotton Plain Top Embellished Non-Stretch Summer Men Tops",
  },
  {
    id: 13,
    name: "Richard Mille 011-01 Automatic Flyback Chronograph Roberto Mancini",
    category: "Sepatu",
    price: 100,
    image: "/images/products/sepatu-1.png",
    isCart: false,
    description: "White Casual Short Sleeve Cotton Plain Top Embellished Non-Stretch Summer Men Tops",
  },
  {
    id: 14,
    name: "Richard Mille 011-01 Automatic Flyback Chronograph Roberto Mancini",
    category: "Sepatu",
    price: 100,
    image: "/images/products/sepatu-2.png",
    isCart: false,
    description: "White Casual Short Sleeve Cotton Plain Top Embellished Non-Stretch Summer Men Tops",
  },
  {
    id: 15,
    name: "Richard Mille 011-01 Automatic Flyback Chronograph Roberto Mancini",
    category: "Sepatu",
    price: 100,
    image: "/images/products/sepatu-3.png",
    isCart: false,
    description: "White Casual Short Sleeve Cotton Plain Top Embellished Non-Stretch Summer Men Tops",
  },
];